Initial PR for exchange discovery.
w3c-ccg/vc-api pull request #268
Opened 2022-02-24 21:02 UTC by mavarley

To address Issue #259 .

2022-02-24 21:20 UTC, TallTed commented on holder.yml
> +      summary: provides a discovery endpoint for the exchanges supported by this sserver endpoint.
```suggestion
      summary: provides a discovery endpoint for the exchanges supported by this server endpoint.
```

2022-02-24 21:22 UTC, TallTed commented on holder.yml
> +        the protocol specification name or type, or a url to a spec. Clients consuming this
```suggestion
        the protocol specification name or type, or a URL to a spec. Clients consuming this 
```

2022-03-01 01:02 UTC, msporny commented on holder.yml
> +                  "credential-refresh" : "CredentialRefresh2020",
The way this is expressed in a VC is the following:
```
    "refreshService": {
      "type": "UnmediatedRefresh2021",
      "url": "https://example.edu/exchanges/refresh-degree",
      "validAfter": "2021-09-01T19:23:24Z"
    },
```

could map to this like so:

```
    "https://example.edu/exchanges/refresh-degree": {
      "type": "UnmediatedRefresh2021",
    },
```

Could be a proper JSON-LD object with semantics (not saying this is a good idea, just trying it out):

```
  "@context": ["https://w3id.org/vc/api/v1",  "https://w3id.org/vc-refresh-2021/v1"],
  "service": [{
    "type": "UnmediatedRefresh2021", 
    "serviceEndpoint": "https://example.edu/exchanges/refresh-degree"
  }]
```

2022-03-01 21:05 UTC, OR13 approved these changes
approved if change suggestions are accepted.

2022-03-01 21:48 UTC, OR13 commented on holder.yml
> +  /exchanges/:
```suggestion
  /exchanges:
```

2022-03-01 21:50 UTC, OR13 requested changes
I would like the response example to reflect real world examples, support paging, etc...

2022-03-01 21:51 UTC, OR13 commented on holder.yml
> +                  type: string
don't return a map... return an array with the potential to support paging, etc.

2022-03-01 21:51 UTC, OR13 commented on holder.yml
> +                additionalProperties:
not sure this is valid yaml definition... looks a bit odd.

2022-03-01 21:52 UTC, OR13 commented on holder.yml
> +          description: a map of the exchange-id endpoints to protocols those exchanges support.
```json
{
    "totalItems": 8,
    "tutorials": [...],
    "totalPages": 3,
    "currentPage": 1
}
```

or similar.

2022-03-02 17:58 UTC, mavarley commented on holder.yml
> +          description: a map of the exchange-id endpoints to protocols those exchanges support.
what are "tutorials" ?

2022-03-20 18:17 UTC, msporny commented
This PR is awaiting a response on pagination. I expect the same applies to GET in PR #271.

2022-03-21 13:36 UTC, OR13 requested changes
API still does not define `items` or consider a world where the response might be too large for one page... we don't need to define all the pagination machinery to approve the PR, but we should be able to see how it could be defined in the future.

2022-03-22 15:39 UTC, OR13 approved these changes

2022-05-17 20:29 UTC, msporny commented on holder.yml
> +                  "excahnges" : [
```suggestion
                  "exchanges" : [
```

2022-05-17 20:35 UTC, msporny commented
The group discussed this on the 2022-05-17 call. There were no objections to merging the PR.

2022-05-17 20:38 UTC, jandrieu commented
How does this PR support the naming of the components for the endpoints?

This continues to be a failing. Without identifying which component MUST implement or MAY implement any particular endpoint, it is hard to understand what is happening.

2022-06-12 20:55 UTC, msporny commented
Still waiting on a re-base on this @mavarley to resolve conflicts -- ping.

2022-08-16 01:03 UTC, msporny commented
> Still waiting on a re-base on this @mavarley to resolve conflicts -- ping.

Second ping...

2022-08-16 20:20 UTC, msporny commented
We discussed this on the 2022-08-16 call and it was decided that we will merge this PR by the following weekend. Either @mavarley will rebase and merge or @msporny will rebase and merge -- whoever gets to it first.

2022-08-17 18:17 UTC, TallTed commented on index.html
> +the Holder App supports the App's protocol requriements on a particular endpoint,
```suggestion
the Holder App supports the App's protocol requirements on a particular endpoint, 
```

2022-08-17 18:42 UTC, merged

2022-08-17 18:42 UTC, mavarley commented
I think all the merging and edit suggestion have been applied properly. Merging.