Fix existing CI/CD pipeline and add linting
w3c-ccg/vc-api pull request #294
Opened 2022-06-14 16:23 UTC by brownoxford

This PR fixes the existing CI/CD workflow for building and publishing OAS documentation to the /api subfolder of GH pages, and it also adds a new linting workflow.

Fixes #277, Resolves #221

2022-06-14 16:38 UTC, mkhraisha approved these changes

2022-06-15 17:17 UTC, TallTed requested changes
minor typo fixes

2022-06-15 17:17 UTC, TallTed commented on .github/workflows/generate-docs.yaml
> +      # Check out repo, setup node, and install dependencies.
```suggestion
      # Check out repo, set up node, and install dependencies.
```

2022-10-09 23:16 UTC, msporny approved these changes

2022-10-09 23:16 UTC, merged