Replace all references/occurences of the term 'VC HTTP API' with 'VC API'
w3c-ccg/vc-api pull request #299
Opened 2022-08-03 16:33 UTC by PatStLouis

Following the VC-API working group meeting on 2022-08-03, it was clarified to me that there has been a previous voted decision to refer to this spec as the VC-API and not VC-HTTP-API for simplicity. This is a great decision in my opinion however I noticed a lot of artifact remaining through the repository referring to HTTP. To avoid ambiguity I suggest to remove all mention of VC-HTTP-API when referring to this specification. There is still mention of HTTP-API in the diagram directory and in various .png files, otherwise I think I got most of it.

2022-08-07 15:38 UTC, msporny requested changes
Overall, +1 to the PR, thank you for raising it!

There is only one minor change request before we can merge, IMHO.

2022-08-07 15:38 UTC, msporny commented on index.html
> +    subtitle: "A API for Verifiable Credentials lifecycle management",
```suggestion
    subtitle: "An HTTP API for Verifiable Credentials lifecycle management",
```

This is the only instance that I think we should keep.

2022-08-07 17:56 UTC, dlongley approved these changes
Thanks for doing this PR! +1 to @msporny's comments.

2022-08-07 22:33 UTC, PatStLouis commented
@msporny your suggestion has been committed. Glad to hear this is welcomed. I'm on vacation for 2 weeks starting tomorrow but can have a look at other relevant repositories when I'm back (such as the test-suites and implementations)

2022-08-08 12:47 UTC, peacekeeper approved these changes

2022-08-16 01:02 UTC, msporny approved these changes

2022-08-16 01:02 UTC, msporny commented
Editorial, multiple reviews, changes requested and made, no objections, merging.

2022-08-16 01:02 UTC, merged