Add text about base URL. Fix #244.
w3c-ccg/vc-api pull request #351
Opened 2023-12-12 17:50 UTC by BigBlueHat

2023-12-12 18:14 UTC, TallTed requested changes

2023-12-12 18:14 UTC, TallTed commented on index.html
> +example.com/api).
```suggestion
their base URL MAY be the host name of the server (e.g., <code>example.com</code>), a
subdomain (e.g., <code>api.example.com</code>), or a path within that host (e.g.,
<code>example.com/api</code>).
```

2023-12-13 22:09 UTC, TallTed approved these changes

2024-01-07 19:14 UTC, msporny approved these changes

2024-01-09 20:42 UTC, merged