Add Security Considerations section on deletion.
w3c-ccg/vc-api pull request #360
Opened 2024-01-07 21:13 UTC by msporny

This PR is an attempt to address issue #276 by adding a Security Considerations section on deletion.

2024-01-08 17:26 UTC, TallTed requested changes
minor, human, editorial

2024-01-08 17:26 UTC, TallTed commented on index.html
> +and the side-effects caused by them are out of scope for this specification.
```suggestion
and the side-effects they might cause are out of scope for this specification.
```

2024-01-08 17:26 UTC, TallTed commented on index.html
> +useful feature to provide an entity.
```suggestion
some or all of the original information. This mode of operation can be useful if
there are audit requirements for all credentials and/or presentations over
a particular time period, or if recovering an original credential might be a
useful feature to provide to an entity.
```

2024-01-08 17:26 UTC, TallTed commented on index.html
> +that is outdated and beyond the needs of an audit or when responding to any
```suggestion
that is outdated and beyond the needs of any audit or when responding to any
```

2024-01-08 17:26 UTC, TallTed commented on index.html
> +halted.
```suggestion
When deleting a <a>verifiable credential</a>, handling of its status
information needs to be considered. Some use cases might call for deletion
of a particular <a>verifiable credential</a> to also set the revocation
and suspension bits of that <a>verifiable credential</a>, such that any sort of
status check for the deleted credential fails and use of the credential is
halted.
```

2024-01-08 17:26 UTC, TallTed commented on index.html
> +case.
```suggestion
Given the scenarios above, implementers are advised to allow the system actions
that occur after a delete to be configurable, such that system flexibility is
sufficient to address any <a>verifiable credential</a> use case.
```

2024-01-08 18:48 UTC, brianorwhatever approved these changes

2024-01-09 17:03 UTC, dlongley approved these changes
+1 w/ @TallTed's suggestions.

2024-01-23 19:20 UTC, merged