Add returnCredential option to VerifyOptions
w3c-ccg/vc-api pull request #366
Opened 2024-02-06 20:53 UTC by jrhender

**Draft** PR to address https://github.com/w3c-ccg/vc-api/issues/207

TODO:
- [ ] Fix extra json that is showing up in `index.html`
<img width="980" alt="image" src="https://github.com/w3c-ccg/vc-api/assets/4407464/00de0cd3-1f4e-44d0-9d05-edf85958a60d">

- [ ] Describe what "canonical form" means
- [ ] Mention that the parameter is optional
- [ ] Add return examples
- [ ] Add the feature to the `Verify Presentation` presentation end point

2024-02-06 20:56 UTC, jrhender commented on components/VerifyOptions.yml
> +          type: boolean
Maybe `boolean` is not a valid keyword and this is why the extra json is appearing

2024-02-20 20:42 UTC, jrhender commented on components/VerifyOptions.yml
> +          type: boolean
Fixed by https://github.com/w3c-ccg/vc-api/pull/366/commits/5fa7f3ae6e840587edeb263aa95a0dcc0c3c6b09

2024-02-21 17:39 UTC, TallTed requested changes
trivial, human facing, for clarity

2024-02-21 17:39 UTC, TallTed commented on components/VerifyOptions.yml
> +            Should the verified credential be returned in the response.
```suggestion
            Should the verified credential be returned in the response?
```

2024-02-27 20:13 UTC, msporny approved these changes

2024-02-27 20:13 UTC, msporny commented
Normative, multiple reviews (on the call), changes requested and made, no objections, merging.

2024-02-27 20:13 UTC, merged