update endpoing to use proved
w3c-ccg/vc-api pull request #378
Opened 2024-03-26 19:58 UTC by mkhraisha

Updates all references from proving a presentations to become creating a presentations. 
Changes endpoint from POST `presentations/prove` to POST `presentations`

2024-03-26 20:54 UTC, PatStLouis approved these changes

2024-04-02 18:30 UTC, msporny commented on index.html
> +          /credentials/derive /presentations
```suggestion
          /credentials/derive /presentations/create
```

2024-04-02 18:30 UTC, msporny commented on index.html
> +          data-api-endpoint="post /presentations"></div>
```suggestion
          data-api-endpoint="post /presentations/create"></div>
```

2024-04-02 18:31 UTC, msporny commented on holder.yml
> -  /presentations/prove:
I think the group settled on `/presentations/create` ... we can check in on this during the call today.

2024-04-02 18:36 UTC, msporny requested changes
The group decided to use the `controller` pattern from the REST API Design Guidelines a while ago (which means the API should be `/presentations/create`): 

https://github.com/w3c-ccg/vc-api/?tab=readme-ov-file#style-versioning-and-contribution

2024-04-15 15:26 UTC, mkhraisha commented
I believe on the call we resolved to not use 'presentations/create' is there anything else I should hange in this PR?

2024-04-16 19:09 UTC, dlongley approved these changes

2024-04-16 19:09 UTC, msporny commented
> I believe on the call we resolved to not use 'presentations/create' is there anything else I should hange in this PR?

The group discussed this on 2024-04-16 and agreed that it is good to go as-is. Merging now.

2024-04-16 19:10 UTC, merged