Add error handling section
w3c-ccg/vc-api pull request #389
Opened 2024-06-04 15:03 UTC by PatStLouis

Addresses #383 #340 #331 and #141 

Standing questions:

[RFC 9457](https://www.rfc-editor.org/rfc/rfc9457.html) or [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807)?

What should the relationship with [verification algorithms](https://w3c.github.io/vc-data-model/#algorithms) from the spec be?

Should we define specific error codes for each [ProblemDetails](https://w3c.github.io/vc-data-model/#problem-details)?

Is it fair to assume that if an errors are returned the credential is not verified but if only warning are returned it is verified? (see list of error/warnings in the PR for details)

Keyword [status](https://datatracker.ietf.org/doc/html/rfc7807#section-3.1) vs code...

2024-06-04 18:02 UTC, TallTed requested changes

2024-06-04 19:12 UTC, TallTed approved these changes

2024-06-04 19:26 UTC, msporny commented
The group discussed this on the 2024-06-04 telecon:

> RFC 9457 or RFC 7807?

RFC 9457 should be used.

> What should the relationship with verification algorithms from the spec be?

We shouldn't tie too closely to VCDM v2.0 since the API could be used to issue mDL, mDoc, and other types of digital credentials.

> Should we define specific error codes for each ProblemDetails?

Not yet. We need to make sure we don't mix "HTTP Error Codes" with "ProblemDetails" codes. We need to update the ProblemDetails object to align w/ RFC 9457 (add the "status" field). We need to also figure out (later, in another PR) what to do for things like "error revoked" when validating a VC, and so on.

> Is it fair to assume that if an errors are returned the credential is not verified but if only warning are returned it is verified? (see list of error/warnings in the PR for details)

This feels like a safe assumption to make.

> Keyword status vs code...

"status" is for "HTTP Error Codes" (200, 400, etc.) and "code" is for integer codes returned by low-level libraries.

2024-06-11 19:30 UTC, TallTed requested changes

2024-06-11 19:30 UTC, TallTed commented on index.html
> +        The VerificationResponse object MUST have the verified value set to true if no errors are included.
```suggestion
        Errors are `ProblemDetails` relating to cryptography, data model and malformed context.
        Warnings are `ProblemDetails` relating to statuses and validity periods.

        The `VerificationResponse` object MUST have the verified value set to `false` if an error is included.
        The `VerificationResponse` object MUST have the verified value set to `true` if no errors are included.
```

2024-06-11 19:37 UTC, aljones15 approved these changes
LGTM

2024-06-18 19:15 UTC, msporny commented on index.html
> +            "mediaType": "vc+json+ld",
```suggestion
            "mediaType": "application/vc",
```

2024-06-18 19:22 UTC, merged