Add Service Instances Configuration text
w3c-ccg/vc-api pull request #426
Opened 2024-10-08 16:54 UTC by jrhender

This PR:
- Create a new "Service Instances" section with text to address #419

2024-10-08 17:14 UTC, TallTed requested changes

2024-10-08 17:14 UTC, TallTed commented on index.html
> +Instance configuration MAY include, but is not limited to, credential format, key options, credential status mechanisms or credential templates.
```suggestion
Instance configuration MAY include, but is not limited to, credential format, key options, credential status mechanisms, and/or credential templates.
```

2024-10-08 19:03 UTC, dlongley approved these changes

2024-10-09 15:05 UTC, TallTed commented on index.html
> +Runtime discovery of service instance configuration is not supported by the VC API as it is expected that services are known to coordinator at the time of coordinator deployment.
```suggestion
Runtime discovery of service instance configuration is not supported by the VC API as services are expected to be made known to coordinator at the time of coordinator deployment.
```

2024-10-22 19:39 UTC, msporny commented on index.html
> +Runtime discovery of service instance configuration is not supported by the VC API as services are expected to be known by the coordinator at the time of coordinator deployment.
```suggestion
Service configuration is determined by administrators on per instance basis.
Instance configuration can include, but is not limited to, credential format, key options, credential status mechanisms, and/or credential templates.
Administrators are expected to configure service instances such that `options` included in client requests cannot result in incorrect action or problematic responses by the service.
      </p>
      <p>
A coordinator instance can have access to multiple service instances in order to support different use cases.
Runtime discovery of service instance configuration is not supported by the VC API as services are expected to be known by the coordinator at the time of coordinator deployment.
```

2024-10-22 19:41 UTC, msporny approved these changes

2024-10-22 19:41 UTC, merged